title: Rambling Bramble Podcast
description: "A cozy corner for stories, rambles, and reflection"
baseurl: ""
url: "https://Rambling-Bramble-Podcast.github.io"

theme: null
markdown: kramdown
collections:
  episodes:
    output: true
    permalink: /episodes/:title/

permalink: /:title/
