title: Rambling Bramble Podcast
description: "A cozy corner for stories, rambles, and reflections."
baseurl: "/podcast"
url: "https://rambling-bramble-blog.github.io"

collections:
  episodes:
    output: true
    permalink: /episodes/:title/

theme: null
markdown: kramdown

defaults:
  - scope:
      path: ""
      type: episodes
    values:
      layout: episode

include:
  - feed.xml
