title: Rambling Bramble Podcast
description: "A cozy corner for stories, rambles, and reflection"
url: "https://rambling-bramble-blog.github.io"
baseurl: "/podcast"

theme: null
markdown: kramdown
collections:
  episodes:
    output: true
    permalink: /episodes/:title/

permalink: /:title/
