title: Rambling Bramble Podcast
description: A chaotic podcast filled with stories, rambles, and reflections.
itunes_author: "Rambling Bramble Blog"
itunes_summary: {{ site.description }}
baseurl: "/podcast"
url: "https://rambling-bramble-blog.github.io"

theme: null
markdown: kramdown

collections:
  episodes:
    output: true
    permalink: episodes/:title/

defaults:
  - scope:
      path: ""
      type: episodes
    values:
      layout: episode

include:
  - '_episodes/'

plugins:
  - jekyll-feed
