title: Rambling Bramble Podcast
description: "A cozy corner for stories, rambles, and reflections."
baseurl: "/podcast"
url: "https://rambling-bramble-blog.github.io"

theme: null
markdown: kramdown

collections:
  episodes:
    output: true
    permalink: episodes/:title/

defaults:
  - scope:
      path: ""
      type: episodes
    values:
      layout: episode

include:
  - '_episodes/'
  - 'https://github.com/Rambling-Bramble-Blog/podcast/feed.xml'

plugins:
  - jekyll-feed
